[build]
  base = "my-website"
  command = "npm run build"
  publish = "build"
  environment = { NODE_VERSION = "20", YARN_VERSION = "1.22.19" }

[[plugins]]
  package = "@netlify/plugin-functions-core"
